version: '2'

tasks:
  build-deploy:
    desc: 'Build and deploy'
    dir: src
    cmds:
      - hugo
      - |
        rm -rf ../docs/ && \
        cp -pRP public/ ../docs/ && \
        rm -rf public/
